services:
    plenta.contao_tiny_compress_images.compressor:
        class: Plenta\ContaoTinyCompressImages\TinyPNG\Compressor
        public: true
        arguments:
            - '@contao.framework'
            - '@translator'
            - '@logger'
            - '@http_client'
            - '%kernel.project_dir%'
